[workspace]
members = [
    "queue",
    "kanal_channel",
    "std_channel",
    "tokio_channel",
    "tokio_std_channel",
    "tokio_flume",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_yaml = "^0.9"