[package]
name = "simple-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt-rtt = "0.4.0"
log = "0.4"
env_logger = "0.10"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
heapless = "0.7"

event-listener = "^3.0"

circular-queue = "^0.2"

multiqueue = "^0.3"

rand = "^0.8"

csv = "^1.3"

[[bin]]
name = "async_event"
path = "src/async_event.rs"

[[bin]]
name = "async_event_queue"
path = "src/async_event_queue.rs"

[[bin]]
name = "drop_double"
path = "src/traits/drop_double.rs"

[[bin]]
name = "bounds"
path = "src/traits/bounds.rs"

[[bin]]
name = "empty_bounds"
path = "src/traits/empty_bounds.rs"

[[bin]]
name = "multiple_bounds"
path = "src/traits/multiple_bounds.rs"

[[bin]]
name = "bounds_option"
path = "src/traits/bounds_option.rs"

[[bin]]
name = "new_type_ideome"
path = "src/traits/new_type_ideome.rs"

[[bin]]
name = "associated_items"
path = "src/traits/associated_items/associated_items.rs"

[[bin]]
name = "associated_types"
path = "src/traits/associated_items/associated_types.rs"

[[bin]]
name = "phantom_type"
path = "src/traits/phantom_type/phantom_type.rs"

[[bin]]
name = "add_phantom"
path = "src/traits/phantom_type/add_phantom.rs"

[[bin]]
name = "nested_fn_channel"
path = "src/test_nested_fn/nested_fn_channel.rs"

[[bin]]
name = "nested_fn_multiqueue"
path = "src/test_nested_fn/nested_fn_multiqueue.rs"

[[bin]]
name = "return_dyn_trait"
path = "src/traits/return_dyn_trait.rs"

[[bin]]
name = "operator_overloading"
path = "src/traits/operator_overloading.rs"

[[bin]]
name = "drop_trait"
path = "src/traits/drop_trait.rs"

[[bin]]
name = "iterators"
path = "src/traits/iterators.rs"

[[bin]]
name = "nested_sum"
path = "src/test_nested_fn/nested_sum.rs"

[[bin]]
name = "impl_trait_as_argument_type"
path = "src/traits/impl_trait/impl_trait_as_argument_type.rs"

[[bin]]
name = "impl_trait_as_return_type"
path = "src/traits/impl_trait/impl_trait_as_return_type.rs"

[[bin]]
name = "impl_trait_as_return_closure"
path = "src/traits/impl_trait/impl_trait_as_return_closure.rs"

[[bin]]
name = "impl_trait_as_return_iterator"
path = "src/traits/impl_trait/impl_trait_as_return_iterator.rs"

[[bin]]
name = "trait_clone"
path = "src/traits/trait_clone.rs"

[[bin]]
name = "super_traits"
path = "src/traits/super_traits.rs"

[[bin]]
name = "mut_refs"
path = "src/refs/mut_refs.rs"

[[bin]]
name = "nested_fn_enum"
path = "src/test_nested_fn_enum/nested_fn_enum.rs"

[[bin]]
name = "overlapping_traits"
path = "src/traits/overlapping_traits.rs"
