[package]
name = "log_macro_use"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }

log_macro = { path = "../log_macro" }

sal-core = { git = "https://github.com/a-givertzman/rust-sal-core.git", branch = "Dbg" }