[package]
name = "log_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]

syn = { version = "^2.0", features = ["full"] }
quote = "^1.0"

strfmt = { git = "https://github.com/vitiral/strfmt.git" }