[package]
name = "tokio_std_channel"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11"
#
serde = { workspace = true }
serde_yaml = { workspace = true }

tokio = { version = "^1.43", features = ["full"] }

rand = "^0.9"